# Generated by Django 3.0.6 on 2020-05-07 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='内容', max_length=1024, verbose_name='message')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='is_deleted')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='update time')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
    ]
